import Provider from "@/components/Provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Provider>
					<div className="w-full min-h-screen bg-gray-100 font-mont">
						{/* TOP NAV */}
						<Navbar />
						{/* MAIN CONTENTS HERE */}
						<div className="w-full p-8 flex justify-center">{children}</div>
					</div>
				</Provider>
			</body>
		</html>
	);
}
